"""purchases

Revision ID: 366f42776fc9
Revises: b1258d451d06
Create Date: 2023-06-11 18:28:53.937963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366f42776fc9'
down_revision = 'b1258d451d06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_purchases',
    sa.Column('id_purchases', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('id_product', sa.Integer(), nullable=False, comment='ID product'),
    sa.Column('date_purchases', sa.Date(), nullable=False, comment='Product Name'),
    sa.ForeignKeyConstraint(['id_product'], ['t_product.id_product'], ),
    sa.PrimaryKeyConstraint('id_purchases')
    )
    op.create_index(op.f('ix_t_purchases_id_purchases'), 't_purchases', ['id_purchases'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_purchases_id_purchases'), table_name='t_purchases')
    op.drop_table('t_purchases')
    # ### end Alembic commands ###
